from __future__ import annotations

import argparse
import os
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    from scripts.lib.dataio import display_path, read_json, load_csv, write_csv, write_json
except ModuleNotFoundError:  # pragma: no cover - script execution path
    from lib.dataio import display_path, read_json, load_csv, write_csv, write_json


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
DEFAULT_DELISTING_REPORT_JSON = DATA_DIR / "reports" / "delisting_report.json"
DROP_ENTRIES_CSV = DATA_DIR / "review_overrides" / "drop_entries.csv"
APPLY_REPORT_JSON = DATA_DIR / "reports" / "delisting_apply.json"
APPLY_REPORT_MD = DATA_DIR / "reports" / "delisting_apply.md"
DROP_FIELDS = ["ticker", "exchange", "confidence", "reason"]


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def drop_key(row: dict[str, str]) -> tuple[str, str]:
    return row.get("exchange", ""), row.get("ticker", "")


def classify_candidate(candidate: dict[str, str]) -> str:
    classification = candidate.get("classification", "")
    exchange = candidate.get("exchange", "")
    if classification == "delisted" and exchange == "BSE_IN":
        return "apply_drop_override"
    if classification == "master_absent":
        return "manual_rename_vs_delisting_required"
    if classification == "suspended":
        return "blocked_suspended_kept_by_policy"
    return "manual_unsupported_classification"


def build_drop_row(candidate: dict[str, str]) -> dict[str, str]:
    return {
        "ticker": candidate.get("ticker", ""),
        "exchange": candidate.get("exchange", ""),
        "confidence": "0.99",
        "reason": (
            "Official BSE ListofScripData status is Delisted; generated by "
            "scripts/apply_delistings.py from the gated delisting report."
        ),
    }


def apply_delistings(
    *,
    delisting_report_json: Path = DEFAULT_DELISTING_REPORT_JSON,
    drop_entries_csv: Path = DROP_ENTRIES_CSV,
    report_json: Path = APPLY_REPORT_JSON,
    report_md: Path = APPLY_REPORT_MD,
    apply: bool = False,
) -> dict[str, Any]:
    source = read_json(delisting_report_json, default={}) or {}
    candidates = list(source.get("candidates", []))
    existing_drop_rows = load_csv(drop_entries_csv)
    existing_keys = {drop_key(row) for row in existing_drop_rows}

    applied: list[dict[str, str]] = []
    drafted: list[dict[str, str]] = []
    blocked: list[dict[str, str]] = []
    manual: list[dict[str, str]] = []
    new_drop_rows: list[dict[str, str]] = []

    for candidate in candidates:
        status = classify_candidate(candidate)
        row = {
            "exchange": candidate.get("exchange", ""),
            "ticker": candidate.get("ticker", ""),
            "name": candidate.get("name", ""),
            "isin": candidate.get("isin", ""),
            "classification": candidate.get("classification", ""),
            "status": status,
        }
        if status == "apply_drop_override":
            key = drop_key(row)
            if key in existing_keys:
                applied.append({**row, "status": "already_present_drop_override"})
                continue
            drop_row = build_drop_row(candidate)
            if apply:
                new_drop_rows.append(drop_row)
                existing_keys.add(key)
                applied.append(row)
            else:
                drafted.append({**row, **drop_row})
        elif status.startswith("blocked"):
            blocked.append(row)
        else:
            manual.append(row)

    if apply and new_drop_rows:
        rows = [*existing_drop_rows, *new_drop_rows]
        rows.sort(key=lambda row: (row.get("exchange", ""), row.get("ticker", "")))
        write_csv(drop_entries_csv, DROP_FIELDS, rows)

    summary = {
        "generated_at": utc_now_iso(),
        "apply": apply,
        "delisting_report_json": display_path(delisting_report_json, ROOT),
        "drop_entries_csv": display_path(drop_entries_csv, ROOT),
        "applied_rows": len(applied),
        "drafted_rows": len(drafted),
        "blocked_rows": len(blocked),
        "manual_rows": len(manual),
        "status_counts": dict(sorted(Counter(row["status"] for row in [*applied, *drafted, *blocked, *manual]).items())),
    }
    report = {
        "summary": summary,
        "applied": applied,
        "drafted": drafted,
        "blocked": blocked,
        "manual": manual,
    }
    write_json(report_json, report)
    write_markdown(report_md, report)
    set_github_output("delistings_applied", "true" if apply and new_drop_rows else "false")
    set_github_output("applied_rows", str(len(new_drop_rows)))
    return report


def write_markdown(path: Path, report: dict[str, Any]) -> None:
    summary = report["summary"]
    lines = [
        "# Delisting Apply",
        "",
        f"- Generated at: `{summary['generated_at']}`",
        f"- Apply mode: `{str(summary['apply']).lower()}`",
        f"- Applied rows: `{summary['applied_rows']}`",
        f"- Drafted rows: `{summary['drafted_rows']}`",
        f"- Blocked rows: `{summary['blocked_rows']}`",
        f"- Manual rows: `{summary['manual_rows']}`",
        "",
        "Only BSE candidates with authoritative `classification=delisted` are eligible for automatic drop overrides. `master_absent` rows stay manual until rename-vs-delisting is classified.",
        "",
        "## Status Counts",
        "",
        "| Status | Rows |",
        "|---|---:|",
    ]
    for status, count in summary["status_counts"].items():
        lines.append(f"| {status} | {count} |")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def set_github_output(key: str, value: str) -> None:
    if "GITHUB_OUTPUT" not in os.environ:
        return
    with Path(os.environ["GITHUB_OUTPUT"]).open("a", encoding="utf-8") as handle:
        handle.write(f"{key}={value}\n")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Apply/draft verified delisting candidates.")
    parser.add_argument("--delisting-report-json", type=Path, default=DEFAULT_DELISTING_REPORT_JSON)
    parser.add_argument("--drop-entries-csv", type=Path, default=DROP_ENTRIES_CSV)
    parser.add_argument("--report-json", type=Path, default=APPLY_REPORT_JSON)
    parser.add_argument("--report-md", type=Path, default=APPLY_REPORT_MD)
    parser.add_argument("--apply", action="store_true", help="Write eligible drop overrides. Without this, only draft/report.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    apply_delistings(
        delisting_report_json=args.delisting_report_json,
        drop_entries_csv=args.drop_entries_csv,
        report_json=args.report_json,
        report_md=args.report_md,
        apply=args.apply,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
