from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.lib.dataio import merge_metadata_updates
from scripts.rebuild_dataset import LISTINGS_CSV, is_valid_isin, normalize_sector


DEFAULT_ENTRY_QUALITY_CSV = ROOT / "data" / "reports" / "entry_quality.csv"
DEFAULT_OUTPUT_DIR = ROOT / "data" / "etf_verification"
DEFAULT_REPORT_CSV = DEFAULT_OUTPUT_DIR / "reviewed_source_metadata_backfill.csv"
DEFAULT_REPORT_JSON = DEFAULT_OUTPUT_DIR / "reviewed_source_metadata_backfill.json"
DEFAULT_METADATA_UPDATES_CSV = ROOT / "data" / "review_overrides" / "metadata_updates.csv"

REPORT_FIELDNAMES = [
    "ticker",
    "exchange",
    "field",
    "proposed_value",
    "decision",
    "source_name",
    "source_url",
    "evidence",
]


@dataclass(frozen=True)
class ReviewedSourceUpdate:
    ticker: str
    exchange: str
    field: str
    proposed_value: str
    confidence: str
    source_name: str
    source_url: str
    evidence: str
    replace_existing: bool = False


REVIEWED_SOURCE_UPDATES: tuple[ReviewedSourceUpdate, ...] = (
    ReviewedSourceUpdate(
        "786",
        "PSX",
        "isin",
        "PK0061101017",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-786/",
        "TradingView PSX:786 profile identifies 786 Investments Limited with ISIN PK0061101017; official PSX page confirms the same 786 issuer/listing, explaining the local singular-name abbreviation.",
    ),
    ReviewedSourceUpdate(
        "ACIETF",
        "PSX",
        "isin",
        "PK0088806069",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-ACIETF/",
        "TradingView PSX:ACIETF ETF profile identifies Alfalah Consumer Index ETF units with ISIN PK0088806069; official PSX ETF page confirms the same ACIETF product/listing.",
    ),
    ReviewedSourceUpdate(
        "AGAC",
        "AMS",
        "isin",
        "IE000FHBZDZ8",
        "0.90",
        "Euronext",
        "https://live.euronext.com/en/product/etfs/IE000FHBZDZ8-XAMC",
        "Official Euronext Amsterdam ETF page for AGAC exposes ISIN IE000FHBZDZ8 and market identifier XAMC.",
    ),
    ReviewedSourceUpdate(
        "AGAC",
        "AMS",
        "etf_category",
        "Fixed Income",
        "0.90",
        "BlackRock iShares",
        "https://www.ishares.com/uk/individual/en/products/337224/ishares-core-global-aggregate-bond-ucits-etf",
        "Issuer page describes AGAC as iShares Core Global Aggregate Bond UCITS ETF tracking global investment-grade bonds.",
        replace_existing=True,
    ),
    ReviewedSourceUpdate(
        "AKTR",
        "ATHEX",
        "isin",
        "GRS432003028",
        "0.92",
        "Athens Stock Exchange",
        "https://www.athexgroup.gr/en/market-data/instruments/stocks/AKTR",
        "Official Athens Stock Exchange instrument page identifies symbol AKTR with ISIN GRS432003028.",
    ),
    ReviewedSourceUpdate(
        "BFRE",
        "OTC",
        "etf_category",
        "Equity",
        "0.82",
        "SEC",
        "https://www.sec.gov/Archives/edgar/data/1545440/000158064225001682/umt-westwood_485b.htm",
        "Prospectus identifies Westwood LBRTY Global Equity ETF as tracking the TOBAM LBRTY All World Equity Index.",
    ),
    ReviewedSourceUpdate(
        "BE09442646",
        "Euronext",
        "isin",
        "BE0944264663",
        "0.92",
        "Euronext",
        "https://live.euronext.com/en/product/equities/BE0944264663-XBRU",
        "Official Euronext Brussels equity page identifies SCR-SIBELCO with ISIN BE0944264663; dataset ticker BE09442646 is the same ISIN-derived Sibelco line missing its check digit.",
    ),
    ReviewedSourceUpdate(
        "BOCHGR",
        "ATHEX",
        "isin",
        "IE00BD5B1Y92",
        "0.92",
        "Athens Stock Exchange",
        "https://www.athexgroup.gr/en/market-data/instruments/stocks/BOCHGR",
        "Official Athens Stock Exchange instrument page identifies symbol BOCHGR with ISIN IE00BD5B1Y92.",
    ),
    ReviewedSourceUpdate(
        "GEC",
        "TSX",
        "stock_sector",
        "Consumer Staples",
        "0.90",
        "TMX Money",
        "https://money.tmx.com/en/quote/GEC",
        "Official TMX Money quote page for TSX:GEC identifies Global Education Communities Corp. with sector Consumer Staples and industry Education.",
    ),
    ReviewedSourceUpdate(
        "0HRZ",
        "LSE",
        "stock_sector",
        "Energy",
        "0.80",
        "GlobalData",
        "https://www.globaldata.com/company-profile/cabot-oil-gas-corp/",
        "Company profile describes Cabot/Coterra as an oil and natural gas exploration and production company.",
    ),
    ReviewedSourceUpdate(
        "0NHV",
        "LSE",
        "stock_sector",
        "Industrials",
        "0.80",
        "Yahoo Finance",
        "https://finance.yahoo.com/quote/RECT.BR/profile/",
        "Company profile classifies Recticel under Industrials / Building Products and Equipment.",
    ),
    ReviewedSourceUpdate(
        "AIQ",
        "ASX",
        "stock_sector",
        "Financials",
        "0.78",
        "Intelligent Investor",
        "https://www.intelligentinvestor.com.au/shares/asx-aiq/alternative-investment-trust",
        "Company profile classifies Alternative Investment Trust under Asset Management and Custody Banks.",
    ),
    ReviewedSourceUpdate(
        "ALI",
        "ASX",
        "stock_sector",
        "Financials",
        "0.78",
        "Intelligent Investor",
        "https://www.intelligentinvestor.com.au/shares/asx-ali/argo-global-listed-infrastructure-limited",
        "Company profile classifies Argo Global Listed Infrastructure Limited under Financials.",
    ),
    ReviewedSourceUpdate(
        "AXTRART",
        "SET",
        "isin",
        "THC611010008",
        "0.90",
        "Stock Exchange of Thailand",
        "https://www.set.or.th/en/market/product/stock/quote/AXTRART/company-profile/information",
        "Official SET company profile for AXTRART exposes local ISIN THC611010008.",
    ),
    ReviewedSourceUpdate(
        "BLTN",
        "AMS",
        "isin",
        "DE000A2QP4D2",
        "0.90",
        "Euronext",
        "https://live.euronext.com/en/product/etfs/DE000A2QP4D2-XAMC",
        "Official Euronext Amsterdam ETF page for BLTN exposes ISIN DE000A2QP4D2 and market identifier XAMC.",
    ),
    ReviewedSourceUpdate(
        "BNOBF",
        "OTC",
        "etf_category",
        "Equity",
        "0.82",
        "OBAM Investment Management",
        "https://obam.nl/uploads/files/reports/OBAM-N.V.-Share-Class-Classic-NL0006294035_EN_20240101.pdf",
        "Issuer key information document states OBAM N.V. Classic is an equity fund.",
    ),
    ReviewedSourceUpdate(
        "BREJY",
        "OTC",
        "stock_sector",
        "Financials",
        "0.82",
        "mBank",
        "https://www.mbank.pl/en/about-us/about-mbank/",
        "OTC Markets active screener maps BREJY to MBANK SA UNSP/ADR; issuer about page identifies mBank's banking services for individual, private-banking, SME, corporate, and business clients.",
    ),
    ReviewedSourceUpdate(
        "CRTHF",
        "OTC",
        "stock_sector",
        "Health Care",
        "0.82",
        "CARsgen Therapeutics",
        "https://www.carsgen.com/en/about-us/company-overview/",
        "OTC Markets active security profile maps CRTHF to CARsgen Therapeutics Holdings Limited; issuer company overview describes a biopharmaceutical company developing CAR T-cell therapies.",
    ),
    ReviewedSourceUpdate(
        "NPPSF",
        "OTC",
        "stock_sector",
        "Industrials",
        "0.82",
        "Nippon Sharyo",
        "https://www.n-sharyo.co.jp/business/tetsudo_e/",
        "OTC Markets active security profile maps NPPSF to Nippon Sharyo Ltd.; issuer rolling-stock page describes railway rolling stock manufacturing including trains, metro, AGT, LRV, and monorail products.",
    ),
    ReviewedSourceUpdate(
        "XNJJY",
        "OTC",
        "stock_sector",
        "Industrials",
        "0.82",
        "Goldwind",
        "https://www.goldwind.com/en/about/",
        "OTC Markets active screener maps XNJJY to GOLDWIND SCI&TECH CO ADR; issuer about page describes Goldwind as specializing in wind power solutions and clean-energy infrastructure.",
    ),
    ReviewedSourceUpdate(
        "OPMNF",
        "OTC",
        "stock_sector",
        "Energy",
        "0.84",
        "Oriental Petroleum and Minerals",
        "https://opmc.com.ph/",
        "OTC Markets active security profile maps OPMNF to Oriental Petroleum & Mineral; issuer site identifies Oriental Petroleum and Minerals Corporation as an upstream petroleum exploration and production company.",
    ),
    ReviewedSourceUpdate(
        "FOACW",
        "OTC",
        "stock_sector",
        "Financials",
        "0.82",
        "Finance of America",
        "https://www.financeofamerica.com/",
        "OTC Markets active security profile maps FOACW to Finance of America Companies Inc.; issuer site identifies Finance of America as a reverse-mortgage and home-equity lending business.",
    ),
    ReviewedSourceUpdate(
        "RPTCV",
        "OTC",
        "stock_sector",
        "Real Estate",
        "0.84",
        "Rithm Property Trust",
        "https://www.rithmpropertytrust.com/",
        "OTC Markets news/security context maps RPTCV to Rithm Property Trust Series C preferred stock; issuer investor site identifies Rithm Property Trust as a real-estate investment platform.",
    ),
    ReviewedSourceUpdate(
        "SPMCP",
        "OTC",
        "stock_sector",
        "Financials",
        "0.84",
        "Sound Point Meridian Capital",
        "https://www.soundpointmeridiancap.com/",
        "OTC Markets security context maps SPMCP to Sound Point Meridian Capital preferred shares; issuer investor site identifies Sound Point Meridian Capital as a closed-end investment company.",
    ),
    ReviewedSourceUpdate(
        "SHCC",
        "OTC",
        "stock_sector",
        "Industrials",
        "0.78",
        "MarketScreener",
        "https://www.marketscreener.com/quote/stock/SHI-CORPORATION-120787252/",
        "Exact OTC SHCC profile identifies Shi Corporation with ISIN US78423F1012 and classifies the company under Business Support Services, mapped conservatively to Industrials.",
    ),
    ReviewedSourceUpdate(
        "SDPMP",
        "OTC",
        "name",
        "Sound Point Meridian Capital 8.5% Preferred Shares",
        "0.90",
        "FINRA",
        "https://www.finra.org/sites/default/files/2025-07/UPC-67-2025%20SDPMP.pdf",
        "FINRA UPC advisory identifies SDPMP as Sound Point Meridian Cap with class of security 8.5% Preferred Shares.",
    ),
    ReviewedSourceUpdate(
        "SDPMV",
        "OTC",
        "name",
        "Sound Point Meridian Capital Inc Preferred Shares 8.5%",
        "0.92",
        "FINRA",
        "https://www.finra.org/sites/default/files/2025-07/UPC-66-2025%20SDPMV.pdf",
        "FINRA UPC advisory states symbol SDPMV was issued for Sound Point Meridian Cap Inc Preferred Shares 8.5% (When Issued).",
    ),
    ReviewedSourceUpdate(
        "MCSAV",
        "OTC",
        "name",
        "MicroStrategy Inc 10% Perpetual Strife Preferred Series A",
        "0.92",
        "FINRA",
        "https://www.finra.org/sites/default/files/2025-03/UPC-31-2025-MCSAV%281%29.pdf",
        "FINRA UPC advisory states symbol MCSAV was issued for MicroStrategy Inc 10% Perpetual Strife Preferred Series A (When Issued).",
    ),
    ReviewedSourceUpdate(
        "MCSYV",
        "OTC",
        "name",
        "MicroStrategy Inc 10% Perpetual Stride Preferred Series A",
        "0.92",
        "FINRA",
        "https://www.finra.org/sites/default/files/2025-06/UPC-57-2025-MCSYV.pdf",
        "FINRA UPC advisory states symbol MCSYV was issued for MicroStrategy Inc 10% Perpetual Stride Preferred Series A (When Issued).",
    ),
    ReviewedSourceUpdate(
        "TDSPU",
        "OTC",
        "name",
        "Telephone and Data Systems Inc Depositary Shares 6.625% Series UU Preferred Stock",
        "0.86",
        "Nasdaq / TDS",
        "https://www.nasdaq.com/market-activity/stocks/tds%5Eu",
        "Nasdaq identifies TDS^U as Telephone and Data Systems depositary shares representing Series UU preferred stock; issuer dividend page confirms holders of Series UU depositary shares receive preferred-share dividends.",
    ),
    ReviewedSourceUpdate(
        "DTZ",
        "ASX",
        "stock_sector",
        "Information Technology",
        "0.90",
        "ASX",
        "https://www.asx.com.au/markets/company/DTZ",
        "Official ASX company page identifies Dotz Nano Limited / DTZ in the Technology Hardware & Equipment industry group; ASX listed-company source maps DTZ to the canonical Information Technology sector.",
    ),
    ReviewedSourceUpdate(
        "DTZNY",
        "OTC",
        "stock_sector",
        "Information Technology",
        "0.88",
        "Dotz Nano / ASX",
        "https://dotz.tech/investors/american-depository-receipts-program/",
        "Issuer ADR page states Dotz Nano stock trades on ASX as DTZ and its Level I ADR trades on OTC under DTZNY; official ASX source maps the underlying DTZ listing to Information Technology.",
    ),
    ReviewedSourceUpdate(
        "DTZZF",
        "OTC",
        "stock_sector",
        "Information Technology",
        "0.88",
        "ASX",
        "https://www.asx.com.au/markets/company/DTZ",
        "OTC DTZZF shares the Dotz Nano Limited ordinary-share ISIN AU000000DTZ4 with ASX:DTZ; official ASX source maps the underlying DTZ listing to Information Technology.",
    ),
    ReviewedSourceUpdate(
        "CVW",
        "TSXV",
        "stock_sector",
        "Materials",
        "0.90",
        "TMX Money",
        "https://money.tmx.com/en/quote/CVW",
        "Official TMX Money quote page identifies CVW Sustainable Royalties Inc. / TSXV:CVW with sector Materials and industry Mining.",
    ),
    ReviewedSourceUpdate(
        "CVWFF",
        "OTC",
        "stock_sector",
        "Materials",
        "0.86",
        "StockAnalysis",
        "https://stockanalysis.com/quote/otc/CVWFF/",
        "Exact OTC CVWFF profile identifies CVW Sustainable Royalties Inc. with sector Materials and industry Other Industrial Metals & Mining; the row's name is now OpenFIGI-supported as CVW Sustainable Royalties Inc.",
    ),
    ReviewedSourceUpdate(
        "BENH",
        "OTC",
        "stock_sector",
        "Consumer Staples",
        "0.86",
        "SEC EDGAR",
        "https://data.sec.gov/submissions/CIK0001568139.json",
        "SEC submissions metadata identifies Bio-En Holdings Corp. / CIK 0001568139 with SIC 2050 Bakery Products, mapped conservatively to the canonical Consumer Staples sector.",
    ),
    ReviewedSourceUpdate(
        "RZZN",
        "OTC",
        "stock_sector",
        "Industrials",
        "0.86",
        "SEC EDGAR",
        "https://data.sec.gov/submissions/CIK0001659559.json",
        "SEC submissions metadata identifies Jialijia Group Corp Ltd / CIK 0001659559 with SIC 5090 Wholesale-Misc Durable Goods, mapped conservatively to the canonical Industrials sector.",
    ),
    ReviewedSourceUpdate(
        "UVCL",
        "OTC",
        "stock_sector",
        "Communication Services",
        "0.84",
        "SEC EDGAR",
        "https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000894680&owner=exclude&action=getcompany",
        "SEC company metadata identifies UniverCell Holdings Inc. / CIK 0000894680 with SIC 4813 Telephone Communications, mapped to the canonical Communication Services sector.",
    ),
    ReviewedSourceUpdate(
        "HLOI",
        "OTC",
        "stock_sector",
        "Consumer Staples",
        "0.86",
        "SEC EDGAR",
        "https://data.sec.gov/submissions/CIK0000805902.json",
        "SEC submissions metadata identifies Previsto International Holdings Inc. / CIK 0000805902 with SIC 2840 Soap, Detergents, Cleaning Preparations, Perfumes, Cosmetics, mapped to the canonical Consumer Staples sector.",
    ),
    ReviewedSourceUpdate(
        "DDNFD",
        "OTC",
        "name",
        "Adamera Minerals Corp",
        "0.84",
        "Yahoo Finance",
        "https://finance.yahoo.com/quote/DDNFD/",
        "Exact OTC quote page identifies DDNFD as ADAMERA MINERALS CORP; the normal OTC DDNFF line already maps to Adamera Minerals Corp.",
    ),
    ReviewedSourceUpdate(
        "DDNFD",
        "OTC",
        "stock_sector",
        "Materials",
        "0.82",
        "Adamera Minerals",
        "https://www.adamera.com/",
        "Exact DDNFD quote evidence ties the row to Adamera Minerals Corp; issuer site describes Adamera as exploring for high-grade gold deposits near Republic, Washington.",
    ),
    ReviewedSourceUpdate(
        "PLYFD",
        "OTC",
        "name",
        "Playfair Mining Ltd",
        "0.84",
        "Stock Events",
        "https://stockevents.app/en/stock/PLYFD",
        "Exact PLYFD profile identifies the symbol as Playfair Mining; the normal OTC PLYFF and TSXV PLY lines already map to Playfair Mining Ltd.",
    ),
    ReviewedSourceUpdate(
        "PLYFD",
        "OTC",
        "stock_sector",
        "Materials",
        "0.82",
        "Playfair Mining",
        "https://playfairmining.com/",
        "Exact PLYFD profile evidence ties the row to Playfair Mining; issuer site describes Playfair as a Canadian mineral exploration company with gold projects in Nova Scotia.",
    ),
    ReviewedSourceUpdate(
        "DOWAD",
        "OTC",
        "name",
        "Defeng Solife Holdings Ltd ADR",
        "0.84",
        "Stock Events",
        "https://stockevents.app/en/stock/DOWAD",
        "Exact DOWAD profile lists OTCM US DOWAD for Dowway Holdings Limited; current ADR program evidence identifies the renamed issuer as Defeng Solife Holdings Limited.",
    ),
    ReviewedSourceUpdate(
        "DOWAD",
        "OTC",
        "stock_sector",
        "Communication Services",
        "0.82",
        "Stock Events",
        "https://stockevents.app/en/stock/DOWAD",
        "Exact DOWAD profile says the issuer operates in the Communication sector and describes integrated exhibition and event management, media, and advertising services.",
    ),
    ReviewedSourceUpdate(
        "AMNGV",
        "OTC",
        "name",
        "American National Group Inc Preferred Series D",
        "0.86",
        "FINRA",
        "https://www.finra.org/sites/default/files/2025-01/UPC-03-2025%20AMNGV.pdf",
        "FINRA UPC advisory identifies AMNGV as American National Group Inc Depositary Shares Representing 1/1000TH Int Preferred Series D (When Issued).",
    ),
    ReviewedSourceUpdate(
        "AMNGV",
        "OTC",
        "stock_sector",
        "Financials",
        "0.84",
        "American National",
        "https://www.americannational.com/home/about-us/investor-relations",
        "Exact FINRA AMNGV identity evidence ties the row to American National Group Inc; issuer investor-relations page describes an insurance holding company offering annuities, life insurance, and property and casualty insurance products.",
    ),
    ReviewedSourceUpdate(
        "HZOZD",
        "OTC",
        "name",
        "BetaPro Crude Oil Daily Bull ETF",
        "0.84",
        "Yahoo Finance",
        "https://finance.yahoo.com/quote/HZOZD/history/",
        "Exact Yahoo Finance quote identifies OTC symbol HZOZD as BETAPRO CRUDE OIL DAILY BULL ET.",
    ),
    ReviewedSourceUpdate(
        "HZOZD",
        "OTC",
        "asset_type",
        "ETF",
        "0.86",
        "Yahoo Finance / BetaPro",
        "https://finance.yahoo.com/quote/HZOZD/history/",
        "Exact Yahoo Finance HZOZD quote identifies an ETF line; issuer BetaPro page for the current HOU product identifies BetaPro Crude Oil Leveraged Daily Bull ETF.",
    ),
    ReviewedSourceUpdate(
        "HZOZD",
        "OTC",
        "etf_category",
        "Leveraged/Inverse",
        "0.86",
        "BetaPro",
        "https://betapro.ca/product/hou",
        "Issuer product page states the BetaPro Crude Oil Leveraged Daily Bull ETF seeks up to two times daily exposure to the BetaPro Crude Oil Rolling Futures Index.",
    ),
    ReviewedSourceUpdate(
        "PTRVD",
        "OTC",
        "name",
        "Avila Energy Corporation",
        "0.82",
        "Stock Events",
        "https://stockevents.app/en/stock/PTRVD",
        "Exact PTRVD profile identifies Avila Energy Corporation and describes an integrated energy company producing crude oil, natural gas, and NGLs in Western Canada.",
    ),
    ReviewedSourceUpdate(
        "PTRVD",
        "OTC",
        "stock_sector",
        "Energy",
        "0.82",
        "Stock Events",
        "https://stockevents.app/en/stock/PTRVD",
        "Exact PTRVD profile says PTRVD operates in the Energy sector and describes crude oil, natural gas, and NGL production in Western Canada.",
    ),
    ReviewedSourceUpdate(
        "PMSXF",
        "OTC",
        "name",
        "Grafton Resources Inc",
        "0.86",
        "TheNewswire",
        "https://www.thenewswire.com/press-releases/1AG9F4Gzz-prisma-exploration-announces-name-change.html",
        "Issuer name-change announcement says Prisma Exploration Inc changed its name to Grafton Resources Inc; exact PMSXF market references identify the same renamed issuer.",
    ),
    ReviewedSourceUpdate(
        "PMSXF",
        "OTC",
        "isin",
        "CA38447A1084",
        "0.86",
        "TheNewswire",
        "https://www.thenewswire.com/press-releases/1AG9F4Gzz-prisma-exploration-announces-name-change.html",
        "Issuer name-change announcement gives new ISIN CA38447A1084 after the Prisma Exploration to Grafton Resources Inc name change.",
    ),
    ReviewedSourceUpdate(
        "PMSXF",
        "OTC",
        "stock_sector",
        "Materials",
        "0.84",
        "Stock Events",
        "https://stockevents.app/en/stock/PMSXF",
        "Exact PMSXF profile says the issuer operates in the Materials sector and describes acquisition, exploration, and development of mineral properties in Canada.",
    ),
    ReviewedSourceUpdate(
        "FNMCD",
        "OTC",
        "name",
        "Goldsky Resources",
        "0.86",
        "Goldsky Resources",
        "https://goldskyresources.com/news/launch-of-goldsky-resources/",
        "Issuer launch announcement identifies Goldsky Resources with OTCQX symbol FNMCD after the First Nordic Metals and Mawson Finland merger.",
    ),
    ReviewedSourceUpdate(
        "FNMCD",
        "OTC",
        "stock_sector",
        "Materials",
        "0.84",
        "Goldsky Resources",
        "https://goldskyresources.com/news/launch-of-goldsky-resources/",
        "Issuer launch announcement identifies Goldsky Resources (OTCQX: FNMCD) as a Nordic-focused gold and cobalt developer with the Barsele gold project and Rajapalot gold-cobalt project.",
    ),
    ReviewedSourceUpdate(
        "VGRDF",
        "OTC",
        "name",
        "VANGUARD FNDS PLC EU ETF",
        "0.88",
        "OTC Markets",
        "https://www.otcmarkets.com/research/stock-screener/api/downloadCSV?greyAccess=false&expertAccess=false",
        "OTC Markets active screener identifies VGRDF with official display name VANGUARD FNDS PLC EU ETF.",
    ),
    ReviewedSourceUpdate(
        "VGRDF",
        "OTC",
        "asset_type",
        "ETF",
        "0.88",
        "OTC Markets / Vanguard",
        "https://www.otcmarkets.com/research/stock-screener/api/downloadCSV?greyAccess=false&expertAccess=false",
        "OTC Markets active screener classifies VGRDF / VANGUARD FNDS PLC EU ETF as an ETF, while the dataset row is a stock-typed Vanguard FTSE Developed Europe product.",
    ),
    ReviewedSourceUpdate(
        "VGRDF",
        "OTC",
        "etf_category",
        "Equity",
        "0.88",
        "Vanguard",
        "https://www.vanguard.co.uk/professional/product/etf/equity/9520/ftse-developed-europe-ucits-etf-eur-distributing",
        "Issuer product page identifies Vanguard FTSE Developed Europe UCITS ETF as an equity ETF tracking the FTSE Developed Europe Index.",
    ),
    ReviewedSourceUpdate(
        "IRS2W",
        "BCBA",
        "isin",
        "ARIRSA100224",
        "0.94",
        "Caja de Valores",
        "https://www.bbva.com.ar/content/dam/public-web/argentina/documents/Comunicado_N_12302_Ejercicio_de_Warrants_de_IRSA_en_pesos_argentinos.pdf",
        "Caja de Valores Comunicado 12302 identifies IRSA INVERSIONES Y REPRESENTACIONES warrants with CVSA code 41298 and ISIN ARIRSA100224; BYMA exact symbol source maps IRS2W to that same warrant instrument.",
    ),
    ReviewedSourceUpdate(
        "PNIZF",
        "BCBA",
        "isin",
        "AR0140128668",
        "0.94",
        "Caja de Valores / BYMA",
        "https://contenidos.sba.com.ar/CAJVAL/vistas/Comunicados/HandlerArchivoComunicacion.aspx?id=9049&token=24EhaHqGKqmrJAniIXL5KzEhkjZSjB7blaJGqx828DxUbAqDgTtK1dAwEOUu6KRfGnZJADVuO7TZgLAUWPRhXQ%2FqOgMF9w%3D%3D",
        "BYMA-hosted Caja de Valores Comunicado 12357 identifies FCI NIZUC USD cuotapartes with especie code 26700 and ISIN AR0140128668; BYMA exact symbol source maps PNIZF to that same fund instrument.",
    ),
    ReviewedSourceUpdate(
        "ALRIS",
        "Euronext",
        "stock_sector",
        "Real Estate",
        "0.90",
        "Euronext",
        "https://www.euronext.com/en/about/media/euronext-press-releases/rising-stone-lists-euronext",
        "Official Euronext listing release describes Rising Stone as a luxury real-estate creator and developer.",
    ),
    ReviewedSourceUpdate(
        "ALU",
        "ASX",
        "stock_sector",
        "Materials",
        "0.80",
        "Morningstar",
        "https://www.morningstar.com/stocks/xasx/alu/quote",
        "Company profile describes Alurion Resources as a mineral exploration company focused on bauxite and gallium.",
    ),
    ReviewedSourceUpdate(
        "460280",
        "KRX",
        "isin",
        "KR7460280001",
        "0.76",
        "CBonds",
        "https://cbonds.com/etf/198731/",
        "Exact KRX ticker page identifies KIWOOM KOSEF Genetic Innovation Technology ETF and ISIN KR7460280001.",
    ),
    ReviewedSourceUpdate(
        "460280",
        "KRX",
        "etf_category",
        "Equity",
        "0.76",
        "StockAnalysis",
        "https://stockanalysis.com/quote/krx/460280/holdings/",
        "Exact KRX ticker holdings page classifies the product as an equity ETF with stock holdings.",
    ),
    ReviewedSourceUpdate(
        "CFIBTGRCA",
        "SSE_CL",
        "isin",
        "CL0002474204",
        "0.76",
        "TradingView",
        "https://es.tradingview.com/symbols/BCS-CFIBTGRCA/",
        "Exact Santiago listing page exposes ISIN CL0002474204 for BTG Pactual Renta Comercial Fondo de Inversion.",
    ),
    ReviewedSourceUpdate(
        "CFIBTGRCA",
        "SSE_CL",
        "etf_category",
        "Real Estate",
        "0.80",
        "BTG Pactual Chile",
        "https://app.btgpactual.cl/productos-de-inversion/detail/fondo-de-inversion/cfibtgrca",
        "Issuer product page describes a leased commercial-real-estate portfolio with 424000 square meters.",
    ),
    ReviewedSourceUpdate(
        "CFINHRFLA",
        "SSE_CL",
        "etf_category",
        "Fixed Income",
        "0.80",
        "Nevasa",
        "https://www.nevasa.cl/fondo-inversion/3/",
        "Issuer page for Fondo de Inversion Nevasa Ahorro lists Descripcion: Renta Fija.",
    ),
    ReviewedSourceUpdate(
        "CFND",
        "NYSE",
        "etf_category",
        "Alternative",
        "0.80",
        "C1 Fund",
        "https://www.c1fund.com/",
        "Issuer page describes a closed-end investment fund providing access to the private digital asset ecosystem.",
    ),
    ReviewedSourceUpdate(
        "CVBP",
        "LSE",
        "isin",
        "GB0002290764",
        "0.90",
        "London Stock Exchange",
        "https://www.londonstockexchange.com/stock/CVBP/coventry-building-society/company-page",
        "Official LSE company page for CVBP exposes ISIN GB0002290764 and SEDOL 0229076.",
    ),
    ReviewedSourceUpdate(
        "ALIMTIAZ",
        "BK",
        "stock_sector",
        "Financials",
        "0.78",
        "Decypha",
        "https://www.decypha.com/en/company-list/Al-Imtiaz-Investment-Group-13726",
        "Company profile lists ALIMTIAZ in the Financial Services sector index and Capital Markets industry.",
    ),
    ReviewedSourceUpdate(
        "DIGITUS",
        "BK",
        "stock_sector",
        "Information Technology",
        "0.78",
        "MarketWatch",
        "https://www.marketwatch.com/investing/stock/digitus/company-profile?countrycode=kw&pid=12226119",
        "Company profile classifies Digitus Group under Technology / Networking.",
    ),
    ReviewedSourceUpdate(
        "BTC",
        "ASX",
        "stock_sector",
        "Health Care",
        "0.80",
        "BTC Health",
        "https://www.btchealth.com.au/about-us/",
        "Issuer describes BTC Health as an ASX-listed healthcare investment and medical-products business.",
    ),
    ReviewedSourceUpdate(
        "CAM",
        "ASX",
        "stock_sector",
        "Financials",
        "0.78",
        "Intelligent Investor",
        "https://www.intelligentinvestor.com.au/shares/asx-cam/clime-capital-limited",
        "Company profile classifies Clime Capital Limited under Financials.",
    ),
    ReviewedSourceUpdate(
        "CPIS12",
        "B3",
        "stock_sector",
        "Utilities",
        "0.80",
        "Equatorial Energia Piaui",
        "https://pi.equatorialenergia.com.br/",
        "Issuer page describes Equatorial Energia Piaui as an electric utility operating generation, transmission, and distribution.",
    ),
    ReviewedSourceUpdate(
        "DOUJA-PROM",
        "CSE_MA",
        "stock_sector",
        "Real Estate",
        "0.80",
        "Investing.com",
        "https://www.investing.com/equities/addoha-company-profile",
        "Company profile says Douja Promotion Groupe Addoha operates in the real estate sector.",
    ),
    ReviewedSourceUpdate(
        "FSDV",
        "Euronext",
        "stock_sector",
        "Real Estate",
        "0.90",
        "Euronext",
        "https://live.euronext.com/en/product/equities/FR0000031973-XPAR/company-information",
        "Official Euronext company information describes FSDV as a real-estate developer.",
    ),
    ReviewedSourceUpdate(
        "FCEPL",
        "PSX",
        "isin",
        "PK0096501017",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-FCEPL/",
        "Exact TradingView PSX:FCEPL profile identifies Frieslandcampina Engro Pakistan Limited with ISIN PK0096501017; official PSX page confirms the same FCEPL issuer/listing.",
    ),
    ReviewedSourceUpdate(
        "FDPL",
        "PSX",
        "isin",
        "PK0063401019",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-FDPL/",
        "TradingView PSX:FDPL profile identifies First Dawood Properties Limited with ISIN PK0063401019; official PSX page confirms the same FDPL issuer/listing behind the local shortened name.",
    ),
    ReviewedSourceUpdate(
        "HRPL",
        "PSX",
        "isin",
        "PK0026401015",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-HRPL/",
        "TradingView PSX:HRPL profile identifies Habib Rice Products Ltd. with ISIN PK0026401015; official PSX page confirms the same HRPL issuer/listing behind the local shortened name.",
    ),
    ReviewedSourceUpdate(
        "HBLTETF",
        "PSX",
        "isin",
        "PK0086206072",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-HBLTETF/",
        "TradingView PSX:HBLTETF ETF profile identifies HBL Total Treasury ETF units with ISIN PK0086206072; official PSX ETF page confirms the same HBLTETF product/listing.",
    ),
    ReviewedSourceUpdate(
        "IGIHL",
        "PSX",
        "isin",
        "PK0032601012",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-IGIHL/",
        "TradingView PSX:IGIHL profile identifies IGI Holdings Limited with ISIN PK0032601012; official PSX page confirms the same IGIHL issuer/listing.",
    ),
    ReviewedSourceUpdate(
        "IML",
        "PSX",
        "isin",
        "PK0093001011",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-IML/",
        "TradingView PSX:IML profile identifies Imperial Limited with ISIN PK0093001011; official PSX page confirms the same IML issuer/listing behind the truncated local name.",
    ),
    ReviewedSourceUpdate(
        "IPAK",
        "PSX",
        "isin",
        "PK0111801012",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-IPAK/",
        "TradingView PSX:IPAK profile identifies International Packaging Films Ltd. with ISIN PK0111801012; official PSX page confirms the same IPAK issuer/listing behind the local abbreviation.",
    ),
    ReviewedSourceUpdate(
        "JSGBETF",
        "PSX",
        "isin",
        "PK0082806016",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-JSGBETF/",
        "TradingView PSX:JSGBETF ETF profile identifies JS Global Banking Sector ETF units with ISIN PK0082806016; official PSX ETF page confirms the same JSGBETF product/listing.",
    ),
    ReviewedSourceUpdate(
        "JSMFETF",
        "PSX",
        "isin",
        "PK0086006035",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-JSMFETF/",
        "TradingView PSX:JSMFETF ETF profile identifies JS Momentum Factor ETF units with ISIN PK0086006035; official PSX ETF page confirms the same JSMFETF product/listing.",
    ),
    ReviewedSourceUpdate(
        "LCI",
        "PSX",
        "isin",
        "PK0003101018",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-LCI/",
        "TradingView PSX:LCI profile identifies Lucky Core Industries Limited with ISIN PK0003101018; official PSX page confirms the same LCI issuer/listing behind the local abbreviation.",
    ),
    ReviewedSourceUpdate(
        "LSEFSL",
        "PSX",
        "isin",
        "PK0104901019",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-LSEFSL/",
        "TradingView PSX:LSEFSL profile identifies LSE Financial Services Limited with ISIN PK0104901019; official PSX page confirms the same LSEFSL issuer/listing behind the local shortened name.",
    ),
    ReviewedSourceUpdate(
        "MCBIM",
        "PSX",
        "isin",
        "PK0082101012",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-MCBIM/",
        "TradingView PSX:MCBIM profile identifies MCB Investment Management Limited with ISIN PK0082101012; official PSX page confirms the same MCBIM issuer/listing behind the local shortened name.",
    ),
    ReviewedSourceUpdate(
        "MIIETF",
        "PSX",
        "isin",
        "PK0133706017",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-MIIETF/",
        "TradingView PSX:MIIETF ETF profile identifies Mahaana Islamic Index ETF units with ISIN PK0133706017; official PSX ETF page confirms the same MIIETF product/listing.",
    ),
    ReviewedSourceUpdate(
        "MZNPETF",
        "PSX",
        "isin",
        "PK0087306053",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-MZNPETF/",
        "TradingView PSX:MZNPETF ETF profile identifies Meezan Pakistan ETF units with ISIN PK0087306053; official PSX ETF page confirms the same MZNPETF product/listing.",
    ),
    ReviewedSourceUpdate(
        "NBPGETF",
        "PSX",
        "isin",
        "PK0089106048",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-NBPGETF/",
        "TradingView PSX:NBPGETF ETF profile identifies NBP Pakistan Growth ETF units with ISIN PK0089106048; official PSX ETF page confirms the same NBPGETF product/listing.",
    ),
    ReviewedSourceUpdate(
        "NITGETF",
        "PSX",
        "isin",
        "PK0096106015",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-NITGETF/",
        "TradingView PSX:NITGETF ETF profile identifies NIT Pakistan Gateway ETF units with ISIN PK0096106015; official PSX ETF page confirms the same NITGETF product/listing.",
    ),
    ReviewedSourceUpdate(
        "FTREIT",
        "SET",
        "isin",
        "TH6172010006",
        "0.90",
        "Stock Exchange of Thailand",
        "https://www.set.or.th/en/market/product/stock/quote/FTREIT/company-profile/information",
        "Official SET company profile for FTREIT exposes local ISIN TH6172010006.",
    ),
    ReviewedSourceUpdate(
        "GAUD",
        "NYSE ARCA",
        "etf_category",
        "Equity",
        "0.80",
        "Guinness Atkinson Funds",
        "https://www.gafunds.com/",
        "Issuer page identifies GAUD as the US Dividend Builder ETF investing in US dividend-paying companies.",
    ),
    ReviewedSourceUpdate(
        "GBXA",
        "BATS",
        "etf_category",
        "Alternative",
        "0.78",
        "SEC",
        "https://www.sec.gov/Archives/edgar/data/1479026/000119312524280525/d860898d485bpos.htm",
        "SEC filing identifies Goldman Sachs U.S. Large Cap Buffer 1 ETF, a buffer/structured-outcome ETF.",
    ),
    ReviewedSourceUpdate(
        "GMOC",
        "NYSE ARCA",
        "etf_category",
        "Fixed Income",
        "0.80",
        "GMO",
        "https://www.gmo.com/americas/product-index-page/fixed-income/ultra-short-income-strategy/ultra-short-income-etf/",
        "Issuer page says the ETF invests in low-duration high-quality fixed income securities.",
    ),
    ReviewedSourceUpdate(
        "GENIUS21",
        "BMV",
        "asset_type",
        "ETF",
        "0.82",
        "StockAnalysis",
        "https://stockanalysis.com/quote/bmv/GENIUS21/holdings/",
        "Exact BMV ticker holdings page identifies Actinver Casa De Bolsa SA DE CV - Genius 21 as an ETF.",
    ),
    ReviewedSourceUpdate(
        "GENIUS21",
        "BMV",
        "etf_category",
        "Equity",
        "0.78",
        "StockAnalysis",
        "https://stockanalysis.com/quote/bmv/GENIUS21/holdings/",
        "Exact BMV ticker holdings page lists equity holdings including Microsoft, Mastercard, Visa, Netflix, and ServiceNow.",
    ),
    ReviewedSourceUpdate(
        "GMP",
        "LSE",
        "etf_category",
        "Alternative",
        "0.78",
        "Gabelli Merchant Partners",
        "https://www.gabelli.co.uk/docs/gmp/frep/2025jun30_GMPAnnualReport.pdf",
        "Annual report describes equity/fixed-income investments plus event and merger-arbitrage style portfolio construction.",
    ),
    ReviewedSourceUpdate(
        "GLAS.N0000",
        "CSE_LK",
        "stock_sector",
        "Materials",
        "0.78",
        "Sri Lanka Export Development Board",
        "https://www.srilankabusiness.com/exporters-directory/company-profiles/pgp-glass-ceylon-plc/",
        "Company profile lists PGP Glass Ceylon products as glass bottles and glassware.",
    ),
    ReviewedSourceUpdate(
        "EISP",
        "OSL",
        "isin",
        "NO0003998700",
        "0.86",
        "Eiendomsspar",
        "https://mfn.se/8228unk/a/eiendomsspar/endring-av-aksje-eiendomsspar-as-eisp-f10e3ca1.iframe",
        "Issuer-distributed company action release identifies Eiendomsspar AS with ticker EISP and ISIN NO0003998700.",
    ),
    ReviewedSourceUpdate(
        "ELOO",
        "OSL",
        "isin",
        "NO0011002586",
        "0.92",
        "Euronext",
        "https://live.euronext.com/en/product/equities/NO0011002586-XOSL",
        "Official Euronext Oslo equity page identifies ELOPAK with ISIN NO0011002586.",
    ),
    ReviewedSourceUpdate(
        "IBC",
        "ASX",
        "stock_sector",
        "Financials",
        "0.78",
        "Intelligent Investor",
        "https://www.intelligentinvestor.com.au/shares/asx-ibc/ironbark-balanced-income-limited",
        "Company profile classifies Ironbark Balanced Income Limited under Financials.",
    ),
    ReviewedSourceUpdate(
        "HYCB",
        "AMS",
        "isin",
        "IE00098G6RH2",
        "0.90",
        "Euronext",
        "https://live.euronext.com/en/product/etfs/IE00098G6RH2-XAMC",
        "Official Euronext Amsterdam ETF page for HYCB exposes ISIN IE00098G6RH2 and market identifier XAMC.",
    ),
    ReviewedSourceUpdate(
        "FORE",
        "IDX",
        "isin",
        "ID1000210008",
        "0.92",
        "KSEI",
        "https://web.ksei.co.id/services/registered-securities/shares/lc/FORE",
        "Official KSEI registered-securities page identifies short code FORE, stock exchange IDX, active status, and ISIN ID1000210008.",
    ),
    ReviewedSourceUpdate(
        "IRSX",
        "IDX",
        "isin",
        "ID1000184401",
        "0.92",
        "KSEI",
        "https://web.ksei.co.id/services/registered-securities/shares/lc/IRSX?setLocale=en-US",
        "Official KSEI registered-securities page identifies short code IRSX, stock exchange IDX, active status, and ISIN ID1000184401.",
    ),
    ReviewedSourceUpdate(
        "ETFPESOV",
        "BVL",
        "isin",
        "PEP790058007",
        "0.90",
        "Bolsa de Valores de Lima",
        "https://documents.bvl.com.pe/hhii/OE7591/20260522182101/CANASTA3222052632ETFPESOV.PDF",
        "Exchange-hosted fund document identifies Peru Soberano VanEck El Dorado ID ETF ticker ETFPESOV with ISIN PEP790058007.",
    ),
    ReviewedSourceUpdate(
        "JTINA",
        "PSE_CZ",
        "isin",
        "CZ0008044856",
        "0.90",
        "Prague Stock Exchange",
        "https://www.pse.cz/en/detail/CZ0008044856",
        "Official Prague Stock Exchange detail page identifies J&T ARCH INVESTMENTS SICAV a.s. ticker JTINA with ISIN CZ0008044856.",
    ),
    ReviewedSourceUpdate(
        "WABS",
        "BSE_HU",
        "isin",
        "HU0000120720",
        "0.90",
        "Waberer's Group",
        "https://www.waberers.com/en/investors/shareholder-center/dividend-policy",
        "Issuer shareholder center identifies Waberer's International Nyrt. shares with Budapest Stock Exchange ticker WABERERS, Xetra code WABS, and ISIN HU0000120720.",
    ),
    ReviewedSourceUpdate(
        "ETFCETOPOT",
        "BSE_HU",
        "isin",
        "HU0000734454",
        "0.88",
        "Budapest Stock Exchange",
        "https://bse.hu/pages/company_profile/%24security/OTPSZINERGI9",
        "Official Budapest Stock Exchange issuer page lists Investment Units of OTP CETOP Index-Tracking UCITS ETF Fund A series investment certificate with ticker ETFCETOPOTP and ISIN HU0000734454; dataset row ETFCETOPOT carries the same OTP CETOP ETF product name.",
    ),
    ReviewedSourceUpdate(
        "FORRB",
        "BSE_HU",
        "isin",
        "HU0000066394",
        "0.90",
        "Budapest Stock Exchange",
        "https://bse.hu/pages/company_profile/%24security/FORRAS_T",
        "Official Budapest Stock Exchange issuer page lists Forras B share / FORRAS/OE with ISIN HU0000066394; current BSE trading-parameter files use local shortcut FORRB for FORRAS/OE.",
    ),
    ReviewedSourceUpdate(
        "FUTUR",
        "BSE_HU",
        "isin",
        "HU0000107362",
        "0.90",
        "Budapest Stock Exchange",
        "https://bse.hu/pages/company_profile/%24security/FUTURAQUA",
        "Official Budapest Stock Exchange company profile identifies FuturAqua share ticker FUTURAQUA with ISIN HU0000107362; current BSE trading-parameter files use local shortcut FUTUR for FUTURAQUA.",
    ),
    ReviewedSourceUpdate(
        "MBHJ",
        "BSE_HU",
        "isin",
        "HU0000078175",
        "0.88",
        "Budapest Stock Exchange",
        "https://www.bse.hu/pages/company_profile/%24security/MBHJB/%24acpid0x121190x13?lang=hu",
        "Official Budapest Stock Exchange company profile identifies MBH Jelzalogbank share ticker MBHJB with ISIN HU0000078175; the dataset row MBHJ is the same former Takarek/MBH Jelzalogbank equity line.",
    ),
    ReviewedSourceUpdate(
        "MFMS",
        "QSE",
        "isin",
        "QA000YI47FK6",
        "0.90",
        "Mosanada",
        "https://www.mosanada.qa/mosanada-facilities-management-services-q-p-s-c-completes-its-successful-direct-listing-on-the-qatar-stock-exchange-main-market/",
        "Issuer direct-listing release identifies ticker MFMS on Qatar Stock Exchange with ISIN QA000YI47FK6.",
    ),
    ReviewedSourceUpdate(
        "INETREIT",
        "SET",
        "isin",
        "THA430010001",
        "0.90",
        "Stock Exchange of Thailand",
        "https://www.set.or.th/en/market/product/stock/quote/INETREIT/company-profile/information",
        "Official SET company profile for INETREIT exposes local ISIN THA430010001.",
    ),
    ReviewedSourceUpdate(
        "JIGI",
        "LSE",
        "stock_sector",
        "Financials",
        "0.78",
        "Hargreaves Lansdown",
        "https://www.hl.co.uk/shares/shares-search-results/j/jpmorgan-india-growth-and-income-plc-ord-25p",
        "Exact LSE ticker profile identifies JPMorgan India Growth & Income plc as a United Kingdom investment trust.",
    ),
    ReviewedSourceUpdate(
        "CPIP",
        "JSE",
        "isin",
        "ZAE000083838",
        "0.92",
        "JSE",
        "https://clientportal.jse.co.za/companies-and-financial-instruments/issuer-profile?issuermasterid=4253",
        "Official JSE issuer profile for Capitec Bank Holdings lists instrument CPIP / Capitec Bank Hldgs Pref with ISIN ZAE000083838.",
    ),
    ReviewedSourceUpdate(
        "DSBP",
        "JSE",
        "isin",
        "ZAE000158564",
        "0.92",
        "JSE SENS",
        "https://senspdf.jse.co.za/documents/SENS_20260528_S521951.pdf",
        "JSE SENS issuer announcement for Discovery lists JSE share codes DSY, DSBP and identifies DSBP ISIN ZAE000158564.",
    ),
    ReviewedSourceUpdate(
        "GNDP",
        "JSE",
        "isin",
        "ZAE000071106",
        "0.92",
        "JSE SENS",
        "https://senspdf.jse.co.za/documents/SENS_20260430_S520548.pdf",
        "JSE SENS issuer announcement for Grindrod lists share code GNDP with ISIN ZAE000071106.",
    ),
    ReviewedSourceUpdate(
        "IOC",
        "JSE",
        "isin",
        "ZAE000071072",
        "0.92",
        "JSE",
        "https://www.jse.co.za/jse/instruments/7694",
        "Official JSE instrument page identifies iOCO Limited under code IOC; current JSE SENS issuer announcements list IOC with ISIN ZAE000071072.",
    ),
    ReviewedSourceUpdate(
        "NTCP",
        "JSE",
        "isin",
        "ZAE000081121",
        "0.92",
        "JSE SENS",
        "https://senspdf.jse.co.za/documents/SENS_20251027_S512396.pdf",
        "JSE SENS issuer announcement for Netcare lists preference share code NTCP with ISIN ZAE000081121.",
    ),
    ReviewedSourceUpdate(
        "WTOP20",
        "JSE",
        "isin",
        "ZAE000320792",
        "0.92",
        "JSE SENS",
        "https://senspdf.jse.co.za/documents/SENS_20260210_S516891.pdf",
        "JSE SENS ETF announcement for 10X Wealth Top 20 Capped ETF lists share code WTOP20 with ISIN ZAE000320792.",
    ),
    ReviewedSourceUpdate(
        "ZZD",
        "JSE",
        "isin",
        "ZAE000315768",
        "0.92",
        "JSE",
        "https://clientportal.jse.co.za/companies-and-financial-instruments/issuer-profile?issuermasterid=5764",
        "Official JSE issuer profile for Zeda Limited lists instrument ZZD with ISIN ZAE000315768.",
    ),
    ReviewedSourceUpdate(
        "ORILINA",
        "ATHEX",
        "isin",
        "GRS535003008",
        "0.92",
        "Athens Stock Exchange",
        "https://www.athexgroup.gr/en/market-data/instruments/stocks/ORILINA",
        "Official Athens Stock Exchange instrument page identifies symbol ORILINA with ISIN GRS535003008.",
    ),
    ReviewedSourceUpdate(
        "SOFTWEB",
        "ATHEX",
        "isin",
        "GRS538003005",
        "0.92",
        "Athens Stock Exchange",
        "https://www.athexgroup.gr/en/market-data/instruments/stocks/SOFTWEB",
        "Official Athens Stock Exchange instrument page identifies symbol SOFTWEB with ISIN GRS538003005.",
    ),
    ReviewedSourceUpdate(
        "TRESTATES",
        "ATHEX",
        "isin",
        "GRS534003009",
        "0.92",
        "Athens Stock Exchange",
        "https://www.athexgroup.gr/en/market-data/instruments/stocks/TRESTATES",
        "Official Athens Stock Exchange instrument page identifies symbol TRESTATES with ISIN GRS534003009.",
    ),
    ReviewedSourceUpdate(
        "MBSP",
        "LSE",
        "isin",
        "GB00B0712W15",
        "0.90",
        "London Stock Exchange",
        "https://www.londonstockexchange.com/stock/MBSP/newcastle-building-society/company-page",
        "Official LSE company page for MBSP exposes ISIN GB00B0712W15 and SEDOL B0712W1 for the 6.75% PIBS line.",
    ),
    ReviewedSourceUpdate(
        "JFS",
        "TSX",
        "etf_category",
        "Alternative",
        "0.78",
        "CI Global Asset Management",
        "https://funds.cifinancial.com/en/funds/alternative_investments/JFTStrategiesFund.html",
        "Issuer page places JFT Strategies Fund under alternative investments and describes market-risk mitigation.",
    ),
    ReviewedSourceUpdate(
        "LAYS",
        "NASDAQ",
        "etf_category",
        "Leveraged/Inverse",
        "0.78",
        "ETF.com",
        "https://www.etf.com/LAYS",
        "Exact ticker profile says LAYS targets 200% exposure to NVDA and AMD.",
    ),
    ReviewedSourceUpdate(
        "MPCT",
        "TSX",
        "etf_category",
        "Real Estate",
        "0.80",
        "Dream Impact Trust",
        "https://investors.dream.ca/mpct-unoverview/",
        "Issuer investor page says the trust gives access to real estate development and income properties.",
    ),
    ReviewedSourceUpdate(
        "PCEM",
        "NYSE ARCA",
        "etf_category",
        "Equity",
        "0.76",
        "ETF Database",
        "https://etfdb.com/etf/PCEM/",
        "Exact ticker profile classifies PCEM as emerging-markets ex-China growth equity.",
    ),
    ReviewedSourceUpdate(
        "PIAHCLA",
        "PSX",
        "isin",
        "PK0146501017",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-PIAHCLA/",
        "Exact TradingView PSX:PIAHCLA profile identifies PIA Holding Company Limited Class A with ISIN PK0146501017; official PSX page confirms the same PIAHCLA issuer/listing.",
    ),
    ReviewedSourceUpdate(
        "PIAHCLB",
        "PSX",
        "isin",
        "PK0146501025",
        "0.84",
        "CDC Pakistan / PSX",
        "https://www.cdcpakistan.com/assets/uploads/2025/12/ISIN-with-CFI-Code-as-of-December-23-2025.pdf",
        "Official CDC Pakistan ISIN/CFI list identifies PIA Holding Company Limited - Class B / PIAHCLB with ISIN PK0146501025; official PSX page confirms the same PIAHCLB issuer/listing.",
    ),
    ReviewedSourceUpdate(
        "STYLERS",
        "PSX",
        "isin",
        "PK0143701016",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-STYLERS/",
        "TradingView PSX:STYLERS profile identifies Stylers International Limited with ISIN PK0143701016; official PSX page confirms the same STYLERS issuer/listing behind the local abbreviated name.",
    ),
    ReviewedSourceUpdate(
        "UBLPETF",
        "PSX",
        "name",
        "UBL Pakistan Enterprise ETF",
        "0.84",
        "PSX / TradingView",
        "https://dps.psx.com.pk/etf/UBLPETF",
        "Official PSX ETF page identifies UBLPETF as UBL Pakistan Enterprise Exchange Traded Fund; TradingView/OpenFIGI use the same UBL Pakistan Enterprise ETF identity, replacing the compressed local name.",
    ),
    ReviewedSourceUpdate(
        "UBLPETF",
        "PSX",
        "isin",
        "PK0087206139",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-UBLPETF/",
        "TradingView PSX:UBLPETF ETF profile identifies UBL Pakistan Enterprise ETF units with ISIN PK0087206139; official PSX ETF page confirms the same UBLPETF product/listing.",
    ),
    ReviewedSourceUpdate(
        "WAFI",
        "PSX",
        "isin",
        "PK0016701010",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-WAFI/",
        "TradingView PSX:WAFI profile identifies Wafi Energy Pakistan Limited with ISIN PK0016701010; official PSX page confirms the same WAFI issuer/listing behind the local abbreviated name.",
    ),
    ReviewedSourceUpdate(
        "WASL",
        "PSX",
        "isin",
        "PK0042801016",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-WASL/",
        "TradingView PSX:WASL profile identifies Wasl Mobility Modaraba with ISIN PK0042801016; official PSX page confirms the same WASL issuer/listing behind the local shortened name.",
    ),
    ReviewedSourceUpdate(
        "WAVESAPP",
        "PSX",
        "isin",
        "PK0068401014",
        "0.82",
        "TradingView / PSX",
        "https://www.tradingview.com/symbols/PSX-WAVESAPP/",
        "TradingView PSX:WAVESAPP profile identifies Waves Home Appliances Ltd with ISIN PK0068401014; official PSX page confirms the same WAVESAPP issuer/listing behind the local shortened name.",
    ),
    ReviewedSourceUpdate(
        "RAV",
        "TSX",
        "etf_category",
        "Alternative",
        "0.78",
        "Ravensource",
        "https://www.ravensource.ca/",
        "Issuer page describes distressed securities, alternative credit, and special situations equities.",
    ),
    ReviewedSourceUpdate(
        "NCC",
        "ASX",
        "stock_sector",
        "Financials",
        "0.78",
        "The Motley Fool",
        "https://www.fool.com/quote/asx/ncc/",
        "Company profile classifies NAOS Emerging Opportunities under Financials / Capital Markets.",
    ),
    ReviewedSourceUpdate(
        "NSC",
        "ASX",
        "stock_sector",
        "Financials",
        "0.78",
        "Intelligent Investor",
        "https://www.intelligentinvestor.com.au/shares/asx-nsc/naos-small-cap-opportunities-company-limited",
        "Company profile classifies NAOS Small Cap Opportunities Company Limited as Financials.",
    ),
    ReviewedSourceUpdate(
        "PCI",
        "ASX",
        "stock_sector",
        "Financials",
        "0.78",
        "Perpetual",
        "https://www.perpetual.com.au/asset-management/listed-investment-vehicles/income/overview/",
        "Issuer page says Perpetual Credit Income Trust invests in diversified credit and fixed-income assets.",
    ),
    ReviewedSourceUpdate(
        "PARA.N0000",
        "CSE_LK",
        "stock_sector",
        "Industrials",
        "0.78",
        "MarketScreener",
        "https://www.marketscreener.com/quote/stock/PARAGON-CEYLON-PLC-20703708/company/",
        "Company profile describes printing, stationery, and related business support supplies activities.",
    ),
    ReviewedSourceUpdate(
        "SPT6",
        "XETRA",
        "stock_sector",
        "Information Technology",
        "0.80",
        "Beta Systems",
        "https://www.betasystems.com/company/about-us",
        "Issuer page describes Beta Systems as a software company providing IT automation and software applications.",
    ),
    ReviewedSourceUpdate(
        "DX2J",
        "XETRA",
        "isin",
        "LU0322253906",
        "0.88",
        "DWS Xtrackers",
        "https://etf.dws.com/en-gb/LU0322253906-msci-europe-small-cap-ucits-etf-1c/",
        "Issuer product page identifies Xtrackers MSCI Europe Small Cap UCITS ETF 1C with ISIN LU0322253906; exchange references map the XETRA short code DX2J to the same share class.",
    ),
    ReviewedSourceUpdate(
        "DXS7",
        "XETRA",
        "isin",
        "LU0322252924",
        "0.88",
        "DWS Xtrackers",
        "https://etf.dws.com/en-gb/LU0322252924-vietnam-swap-ucits-etf-1c/",
        "Issuer product page identifies Xtrackers Vietnam Swap UCITS ETF 1C with ISIN LU0322252924; exchange references map the XETRA short code DXS7 to the same share class.",
    ),
    ReviewedSourceUpdate(
        "XFRD",
        "XETRA",
        "isin",
        "DE000A1KJHG8",
        "0.90",
        "DWS Xtrackers",
        "https://etf.dws.com/de-de/etc/DE000A1KJHG8-xtrackers-physical-rhodium-etc-eur/",
        "Issuer product page identifies Xtrackers Physical Rhodium ETC (EUR) with ISIN DE000A1KJHG8 and exchange ticker XFRD GY; Deutsche Boerse page lists symbol XFRD with the same ISIN.",
    ),
    ReviewedSourceUpdate(
        "STECH",
        "OSL",
        "stock_sector",
        "Industrials",
        "0.82",
        "Euronext",
        "https://www.euronext.com/en/about/media/euronext-press-releases/soiltech-lists-euronext-expand-oslo",
        "Official Euronext listing release describes Soiltech as a cleantech service provider for water and industrial waste-stream treatment.",
    ),
    ReviewedSourceUpdate(
        "TCF",
        "ASX",
        "stock_sector",
        "Real Estate",
        "0.80",
        "360 Capital",
        "https://www.360capital.com.au/tcf",
        "Issuer page identifies 360 Capital Mortgage REIT as providing credit opportunities secured by Australian real estate assets.",
    ),
    ReviewedSourceUpdate(
        "TDEX",
        "SET",
        "isin",
        "THSE50070002",
        "0.90",
        "Stock Exchange of Thailand",
        "https://www.set.or.th/en/market/product/etf/quote/tdex/factsheet",
        "Official SET ETF factsheet for TDEX exposes local ISIN THSE50070002.",
    ),
    ReviewedSourceUpdate(
        "TROLLEY",
        "BK",
        "stock_sector",
        "Consumer Discretionary",
        "0.82",
        "Decypha",
        "https://beta1.decypha.com/en/company-list/Trolley-General-Trading-Co-K-S-C-P-318923",
        "Company profile lists Trolley in the Consumer Discretionary sector index and Drug & Food Retail industry.",
    ),
    ReviewedSourceUpdate(
        "OBIO3",
        "B3",
        "stock_sector",
        "Consumer Staples",
        "0.78",
        "Oleoplan",
        "https://www.oleoplan.com.br/en/the-oleoplan/who-we-are/",
        "Issuer page says Oleoplan has been active in soybean processing and operates biodiesel production and soybean-crushing units.",
    ),
    ReviewedSourceUpdate(
        "RVRB",
        "BATS",
        "etf_category",
        "Equity",
        "0.80",
        "Vox Populi ETF",
        "https://voxpopuli-etf.com/",
        "Issuer page describes the renamed VOXP/RVRB fund as a long-only diversified equity fund.",
    ),
    ReviewedSourceUpdate(
        "SBSA",
        "LSE",
        "isin",
        "GB0004440623",
        "0.90",
        "London Stock Exchange",
        "https://www.londonstockexchange.com/stock/SBSA/skipton-building-society/company-page",
        "Official LSE company page for SBSA exposes ISIN GB0004440623 and SEDOL 0444062.",
    ),
    ReviewedSourceUpdate(
        "TOAK",
        "NYSE ARCA",
        "etf_category",
        "Alternative",
        "0.80",
        "Twin Oak ETFs",
        "https://twinoaketfs.com/TOAK",
        "Issuer page says TOAK uses defined-risk options to generate absolute return with low price volatility.",
    ),
    ReviewedSourceUpdate(
        "EIRE.P",
        "TSXV",
        "asset_type",
        "Stock",
        "0.88",
        "TMX Money",
        "https://money.tmx.com/en/quote/EIRE.P%3APUR",
        "Official TMX quote page identifies Monaghan Capital Fund Ltd. as a TSXV capital pool company.",
    ),
    ReviewedSourceUpdate(
        "EWQQF",
        "OTC",
        "etf_category",
        "Equity",
        "0.82",
        "Invesco",
        "https://www.invesco.com/uk/en/financial-products/etfs/invesco-eqqq-nasdaq-100-ucits-etf-dist.html",
        "Issuer product page identifies the Invesco EQQQ Nasdaq-100 UCITS ETF asset class as Equity.",
    ),
    ReviewedSourceUpdate(
        "EIRE.P",
        "TSXV",
        "stock_sector",
        "Financials",
        "0.78",
        "FinancialFilings",
        "https://financialfilings.com/companies/monaghan-capital-fund-ltd/",
        "Reviewed company-profile source classifies Monaghan Capital Fund Ltd. under financial and insurance activities.",
    ),
    ReviewedSourceUpdate(
        "RCR.P",
        "TSXV",
        "asset_type",
        "Stock",
        "0.88",
        "TMX Money",
        "https://money.tmx.com/en/quote/RCR.P",
        "Official TMX quote page identifies Canna 8 Investment Trust as a TSXV listed stock quote, not an ETF product.",
    ),
    ReviewedSourceUpdate(
        "RCR.P",
        "TSXV",
        "stock_sector",
        "Financials",
        "0.78",
        "StockAnalysis",
        "https://stockanalysis.com/quote/tsxv/RCR.P/company/",
        "Reviewed company-profile source classifies Canna 8 Investment Trust as Financials / Shell Companies.",
    ),
    ReviewedSourceUpdate(
        "RENT.P",
        "TSXV",
        "stock_sector",
        "Financials",
        "0.90",
        "TMX Money",
        "https://money.tmx.com/en/quote/RENT.P%3AAPH",
        "Official TMX quote page classifies Shine Box Capital Corp. under Finance / Diversified Financial Services.",
    ),
    ReviewedSourceUpdate(
        "LSX",
        "ASX",
        "stock_sector",
        "Financials",
        "0.78",
        "Intelligent Investor",
        "https://www.intelligentinvestor.com.au/shares/asx-lsx/lion-selection-group-limited",
        "Company profile classifies Lion Selection Group Limited under Financials.",
    ),
    ReviewedSourceUpdate(
        "WAM",
        "ASX",
        "stock_sector",
        "Financials",
        "0.78",
        "Intelligent Investor",
        "https://www.intelligentinvestor.com.au/shares/asx-wam/wam-capital-limited",
        "Company profile classifies WAM Capital Limited under Diversified Financial Services.",
    ),
    ReviewedSourceUpdate(
        "VNCUF",
        "OTC",
        "etf_category",
        "Equity",
        "0.82",
        "VanEck",
        "https://www.vaneck.com/uk/en/investments/defense-etf/",
        "Issuer product page describes VanEck Defense UCITS ETF as exposure to companies involved in defense-related industries.",
    ),
    ReviewedSourceUpdate(
        "WMA",
        "ASX",
        "stock_sector",
        "Financials",
        "0.78",
        "Yahoo Finance",
        "https://finance.yahoo.com/quote/WMA.AX/",
        "Company profile classifies WAM Alternative Assets Limited under Asset Management / Financial Services.",
    ),
    ReviewedSourceUpdate(
        "ZYNS",
        "TSX",
        "stock_sector",
        "Consumer Staples",
        "0.90",
        "TMX Money",
        "https://money.tmx.com/en/quote/ZYNS",
        "Official TMX quote page classifies Philip Morris CDR under Consumer Staples / Tobacco.",
    ),
    ReviewedSourceUpdate(
        "TTE",
        "NYSE",
        "isin",
        "FR0000120271",
        "0.94",
        "TotalEnergies",
        "https://totalenergies.com/investors/shares-and-dividends/totalenergies-shares/totalenergies-shares-listed-on-the-nyse",
        "Official TotalEnergies investor page says NYSE-listed ordinary shares are transferable with the European ordinary-share line and identifies the European market shares by ISIN FR0000120271; Fidelity's NYSE TTE quote also reports ISIN FR0000120271.",
    ),
    ReviewedSourceUpdate(
        "WT",
        "NYSE",
        "asset_type",
        "Stock",
        "0.90",
        "WisdomTree Investor Relations",
        "https://ir.wisdomtree.com/",
        "Issuer investor-relations page says WisdomTree common stock is listed on NYSE under symbol WT.",
    ),
    ReviewedSourceUpdate(
        "WT",
        "NYSE",
        "stock_sector",
        "Financials",
        "0.82",
        "WisdomTree",
        "https://www.wisdomtree.com/",
        "Issuer describes WisdomTree as a financial services and asset-management business.",
    ),
    ReviewedSourceUpdate(
        "XACTC25",
        "CPH",
        "etf_category",
        "Equity",
        "0.80",
        "Nasdaq Copenhagen",
        "https://view.news.eu.nasdaq.com/view?id=b284a0c1d7feb653eaddfa76545a17123&lang=en",
        "Nasdaq notice identifies XACTC25/SE0011452127 as an ETF tracking the OMX Copenhagen 25 equity index.",
    ),
)


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def load_listing_rows(path: Path = LISTINGS_CSV) -> dict[tuple[str, str], dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    return {(row["ticker"], row["exchange"]): row for row in rows}


def load_entry_quality_issue_keys(path: Path = DEFAULT_ENTRY_QUALITY_CSV) -> set[tuple[str, str]]:
    if not path.exists():
        return set()
    with path.open(newline="", encoding="utf-8") as handle:
        return {
            (row["ticker"], row["exchange"])
            for row in csv.DictReader(handle)
            if (
                "missing_etf_category" in row.get("issue_types", "").split("|")
                or "expected_missing_primary_isin" in row.get("issue_types", "").split("|")
                or "missing_stock_sector" in row.get("issue_types", "").split("|")
            )
        }


def validate_update(update: ReviewedSourceUpdate, target: dict[str, str] | None) -> str:
    if target is None:
        return "missing_target_row"
    if update.field == "etf_category":
        normalized = normalize_sector(update.proposed_value, "ETF")
        if normalized != update.proposed_value:
            return "invalid_etf_category"
        if target.get("asset_type") != "ETF":
            return "target_not_etf"
        if target.get("etf_category") == update.proposed_value:
            return "accept"
        if target.get("etf_category"):
            if update.replace_existing:
                return "accept"
            return "already_has_etf_category"
        return "accept"
    if update.field == "stock_sector":
        normalized = normalize_sector(update.proposed_value, "Stock")
        if normalized != update.proposed_value:
            return "invalid_stock_sector"
        return "accept"
    if update.field == "asset_type":
        if update.proposed_value not in {"Stock", "ETF"}:
            return "invalid_asset_type"
        if target.get("asset_type") == update.proposed_value:
            return "accept"
        return "accept"
    if update.field == "name":
        if not update.proposed_value.strip():
            return "invalid_name"
        if target.get("name") == update.proposed_value:
            return "accept"
        return "accept"
    if update.field == "isin":
        if not is_valid_isin(update.proposed_value):
            return "invalid_isin"
        if target.get("isin") == update.proposed_value:
            return "accept"
        if target.get("isin"):
            return "already_has_isin"
        return "accept"
    return "unsupported_field"


def evaluate_updates(
    updates: tuple[ReviewedSourceUpdate, ...],
    listing_rows: dict[tuple[str, str], dict[str, str]],
    *,
    issue_keys: set[tuple[str, str]] | None = None,
    exchanges: set[str] | None = None,
) -> list[dict[str, Any]]:
    issue_keys = issue_keys or set()
    results: list[dict[str, Any]] = []
    working_rows = {key: dict(row) for key, row in listing_rows.items()}
    for update in updates:
        key = (update.ticker, update.exchange)
        if exchanges and update.exchange not in exchanges:
            continue
        target = working_rows.get(key)
        decision = validate_update(update, target)
        if decision == "accept" and target is not None:
            target[update.field] = update.proposed_value
        results.append(
            {
                "ticker": update.ticker,
                "exchange": update.exchange,
                "field": update.field,
                "proposed_value": update.proposed_value,
                "confidence": update.confidence,
                "source_name": update.source_name,
                "source_url": update.source_url,
                "evidence": update.evidence,
                "decision": decision,
            }
        )
    return results


def build_metadata_updates(results: list[dict[str, Any]]) -> list[dict[str, str]]:
    updates: list[dict[str, str]] = []
    for result in results:
        if result["decision"] != "accept":
            continue
        updates.append(
            {
                "ticker": result["ticker"],
                "exchange": result["exchange"],
                "field": result["field"],
                "decision": "update",
                "proposed_value": result["proposed_value"],
                "confidence": result["confidence"],
                "reason": (
                    "Reviewed exact-listing source evidence mapped "
                    f"{result['exchange']}::{result['ticker']} {result['field']} to "
                    f"{result['proposed_value']}. Evidence: {result['evidence']} "
                    f"Source: {result['source_url']}"
                ),
            }
        )
    return updates


def write_report_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=REPORT_FIELDNAMES, lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in REPORT_FIELDNAMES})


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Backfill exact reviewed source metadata updates.")
    parser.add_argument("--listings-csv", type=Path, default=LISTINGS_CSV)
    parser.add_argument("--entry-quality-csv", type=Path, default=DEFAULT_ENTRY_QUALITY_CSV)
    parser.add_argument("--csv-out", type=Path, default=DEFAULT_REPORT_CSV)
    parser.add_argument("--json-out", type=Path, default=DEFAULT_REPORT_JSON)
    parser.add_argument("--metadata-updates-csv", type=Path, default=DEFAULT_METADATA_UPDATES_CSV)
    parser.add_argument("--exchange", action="append", help="Restrict to one or more internal exchanges.")
    parser.add_argument("--apply", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    listing_rows = load_listing_rows(args.listings_csv)
    issue_keys = load_entry_quality_issue_keys(args.entry_quality_csv)
    results = evaluate_updates(
        REVIEWED_SOURCE_UPDATES,
        listing_rows,
        issue_keys=issue_keys,
        exchanges=set(args.exchange or []),
    )
    metadata_updates = build_metadata_updates(results)

    write_report_csv(args.csv_out, results)
    args.json_out.parent.mkdir(parents=True, exist_ok=True)
    args.json_out.write_text(json.dumps(results, indent=2, sort_keys=True), encoding="utf-8")

    if args.apply and metadata_updates:
        merge_metadata_updates(args.metadata_updates_csv, metadata_updates)

    print(
        json.dumps(
            {
                "accepted_updates": len(metadata_updates),
                "applied": args.apply,
                "csv_out": display_path(args.csv_out),
                "decision_counts": dict(Counter(row["decision"] for row in results)),
                "json_out": display_path(args.json_out),
            },
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
